version: 2

sources:
  - name: staging
    database: watchful-augury-411213
     # For postgres:
      #database: production
    schema: trips_data_all

      # loaded_at_field: record_loaded_at
    tables:
      - name: green_tripdata
      - name: yellow_tripdata
         # freshness:
           # error_after: {count: 6, period: hour}
      - name: fhv_tripdata

models:
    - name: stg_fhv_tripdata
      description: >
        This data dictionary describes FHV trip data. Each row represents a single trip in an FHV. 
      columns:
          - name: dispatching_base_num
            description: Dispatching_base_num The TLC Base License Number of the base that dispatched the trip
          - name: pickup_datetime 
            description: The date and time of the trip pick-up
          - name: dropOff_datetime 
            description: The date and time of the trip dropoff
          - name: PULocationID 
            description: TLC Taxi Zone in which the trip began
          - name: DOLocationID 
            description: TLC Taxi Zone in which the trip ended
          - name: SR_Flag 
            description: Indicates if the trip was a part of a shared ride chain offered by a
                High Volume FHV company (e.g. Uber Pool, Lyft Line). For shared
                trips, the value is 1. For non-shared rides, this field is null.